version: '3'
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
